### PR TITLE
make TableStyle type consistent with html elements

### LINKED ISSUE #6: Use consistent naming in  TableStyle
```
data TableStyle = 
  TableStyle { 
    table   :: Level -> Markup -> Markup,
    cell    :: JSemantic -> Markup -> Markup, 
    head    :: JPath -> Markup -> Markup,
    row     :: Markup -> Markup }
```
This is inconsistent with the html elements (which Markup represents). instead:
```
data TableStyle = 
  TableStyle { 
    table   :: Level -> Markup -> Markup,
    td    :: JSemantic -> Markup -> Markup, 
    th    :: JPath -> Markup -> Markup,
    tr     :: Markup -> Markup }
```

### PR DESCRIPTION
**Pull request by brainrape**
fix #6

### CODE REVIEW

**Comment by jdegoes** [comment]
:+1: Thanks!

**Comment by brainrape** [comment]
@jdegoes According to the readme, this qualifies for the bounty.

**Comment by jdegoes** [comment]
Hehe. Nice try. It's the first PR that actually satisfies the requirements of the project.

**Comment by ggPeti** [comment]
No, it's the first PR that gets merged. I am also interested in this project, but if it turns out that you, the maintainer, worded a $2000 bounty challenge imprecisely, my interest is instantly that much lower.

**Comment by jdegoes** [comment]
Yes, the requirements are not fully specified, and yes, the existing wording is imprecise and ambiguous in places. The requirements do not constitute a formal specification. Rather, they're a rough description of what I'm looking for that's useful to get contributors on the same page.

If you're not comfortable with uncertainty and ambiguity, then I wouldn't recommend starting one of these bounty projects. 

In fact, I only recommend starting one of our bounty projects if you want to learn the language, contribute to open source, and build something cool. Don't start them if you're just looking to claim a bounty. Because that may happen, but the reality is that most people who start these projects get a few lines of code into them and then move onto other projects. Which is totally fine.

I do think if you talked to previous bounty winners, they would say they're quite happy with the collaborative process, with the give and take, especially in places where I overlooked requirements that would have been too onerous to fulfill (something only discovered in hindsight).

I'm looking to help sponsor some good, useful open source software, without spending as much time creating formal specs as it would take to actually implement the projects (and we all know how formal specs usually turn out -- they're wrong due or miss important details).

If you don't like any part of this process, then obviously you shouldn't participate. There are a ton of other super cool open source projects that you can contribute to and learn as much or more from than these bounty projects. And at the end of the day, that's exactly why you should contribute to open source: you want to build something fun and learn a ton in the process.

**Comment by ggPeti** [comment]
I had a feeling you were going to pull the "Don't start them if you're just looking to claim a bounty" card. If you read my comment carefully, my concern is that you, the maintainer of this project, are not precise enough to specify the correct conditions for a nontrivial bounty. It makes me question if you are going to make similar oversights in the high level architecture of the project itself.

**Comment by ggPeti** [comment]
But I also don't want this to escalate into a flame, please consider my comment well intended. I am interested in the project regardless of the bounty.

**Comment by jdegoes** [comment]
I've gotten a lot of questions asking for clarification, and I've put those answers back into the spec (including more examples, more precise language, etc.). I hope that no one would try working on this project if the goals aren't clear.

More than that, I trust that whoever ends up working on this project will collaborate with me in identifying sticky issues -- issues that either aren't spec'd out, or are spec'd out incorrectly because they've been written by a flawed human (me) without the benefit of hindsight.

I also hope that by collaborating, the end result will be better and contributors will feel more empowered. Basically, I don't want a translator of specs, I want a partner, and I don't want a relationship of dotting i's and crossing t's, but one of trust and mutual respect, working together for a common good.

And, no offense taken. The feedback so far has been good and useful in improving the spec, and I think this project will end up being a wonderful little library -- and a great (simple) alternative to Datatable for any case where the data is a little messy.

**Comment by rappo** [comment]
@jdegoes I came across this discussion regarding bounties and thought that we, Bountysource.com, could help Slamdata manage your bounty program. Bounties on Bountysource are placed on specific open issues and get paid out to the developer who solves those issues. This greatly reduces the concern around ambiguous bounty definitions, as they're tied directly to the closure of a specific issue. Additionally, I think you could get more for your money while offering potential developers some comfort in knowing the bounties are better defined. For instance, you could post a few $250-500 bounties instead of a $2000 winner-takes-all bounty for the "first PR that meets the project's needs".

Bountysource imports all data from GitHub (among others like Bugzilla and Jira), and GH orgs are "teams" on Bountysource. One already (automatically) exists for Slamdata: https://www.bountysource.com/teams/slamdata/issues

Just a thought. I'd be happy to answer questions, or I can see myself out of this discussion if this is not appropriate.

**Comment by jdegoes** [comment]
We tried about a year ago and Bountysource wasn't quite ready, happy to give it another go (but likely would not break out a small project like this into multiple tickets). What % cut do you take these days?

**Comment by rappo** [comment]
@jdegoes Yeah, a lot has changed (and hopefully improved from your perspective) since you last saw us :). Would love to see you give it another go!

There's a 10% cut when users cash out of Bountysource and no fee for posting a bounty (a $100 bounty costs $100). "Internal" transactions, such as using earned money to create another bounty or donate to a team, are free.

**Pull request merged**
