### PR TITLE
Use Halogen, WIP

### PR DESCRIPTION
**Pull request by paf31**
This is still a work in progress. In particular, 

- [x] `colspan` and `rowspan` still need to be implemented
- [ ] Tests are broken right now
- [x] I removed the `Gen` module to get things building
- [x] Fix example

However, things are building (in `src` at least), and I've made an attempt to make the code a little more idiomatic:

- Using records for `Tree` and `Cell`.
- Type signatures on all functions
- Indentation, general formatting

### CODE REVIEW

**Comment by paf31** [comment]
Ok, the only thing remaining are the StrongCheck tests, which I hope I can port to use Halogen's string renderer tomorrow.

I replaced the previous example with a simple Halogen demo (just a text area and a rendered table). I can work on adding back some of the features of the previous demo if you like.

**Comment by paf31** [comment]
The build is failing because I have to use the master revision of the Halogen repo (since I needed to add a change to support `colspan` and `rowspan`) which Travis doesn't like. I can't release Halogen though, because it contains other breaking changes in master right now.

**Comment by jdegoes** [comment]
Super nice!

**Comment by jdegoes** [comment]
I'll merge this now, but we do need those tests back in before this is wrapped up! :smiling_imp:

**Comment by paf31** [comment]
Sounds good, I'll work on that tonight hopefully.

**Pull request merged**
