### PR TITLE
updated to 0.7

### PR DESCRIPTION
**Pull request by cryogenian**
updated to 0.7 compiler version

* I've hided most exports from `Data.Json.JTable.Internal` 
* Removed tests that rely on internal representation of `JTable` 
* Removed example (because `purescript-halogen` will be updated soon) 
* `JSemantic` unit tests produce error -- I just show produced result of rendering.

### CODE REVIEW

**Comment by jdegoes** [comment]
* The Travis CI build failed.
* A lot of tests were removed and not replaced, which makes it hard to say if the code works.
* There are no examples of how to use it.

**Comment by jdegoes** [comment]
Final review / merge by @garyb

**Comment by cryogenian** [comment]
I'm not sure that deleted tests were necessary. They check that `Json` is correctly parsed to internal representation of headers and tables and other private funcs. I think that assertion on `Json -> JSemantic` and table rendering is enough to say that library works. Does it make sense? 

On the second thought it seems that there won't be anything bad if there will be example depending on halogen's particular commit. I'll add it tomorrow.

**Comment by garyb** [comment]
Testing that way sounds sensible to me, I guess we just need to make sure that the "external" tests cover all the cases they should to ensure the behaviour is correct, if previously some of that was checked with the "internal" tests.

Let me know when you update the example and I'll review/merge.

**Comment by cryogenian** [comment]
Updated

**Pull request merged**
